vim.keymap.set("n", "<leader>xw", function()
  require("trouble").toggle("diagnostics")
end)
vim.keymap.set("n", "[x", function()
  require("trouble").prev()
end)
vim.keymap.set("n", "]x", function()
  require("trouble").next()
end)
vim.keymap.set("n", "<leader>xq", function()
  require("trouble").toggle("quickfix")
end)
vim.keymap.set("n", "<leader>xl", function()
  require("trouble").toggle("loclist")
end)
vim.keymap.set("n", "<leader>rr", function()
  require("trouble").toggle("lsp_references")
end)
