# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "[$all$directory$character](lavender)"
palette = "catppuccin_mocha"

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"
error_symbol = "[](bold red)"

[directory]
style = "lavender"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
format="[took $duration](lavender) "

[golang]
symbol=" "
style="bold cyan"

[nodejs]
symbol="󰛦 "
style="bold blue"

[rust]
symbol="⚙︎ "

[git_branch]
style="bold peach"

[git_status]
style="bold green"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
